### ISSUE TITLE
Trimming the final fit to reduce memory usage

### ISSUE THREAD

**Issue by nkurz** [topepo/caret#90] opened 2014-12-27 23:07 UTC
R has a well deserved reputation as being a memory hog when training models.  In part this is because the defaults tend toward keeping everything that might be used in the theory that this is easier for the user than explicitly specifying which parts they want to keep.   When training a single model, this is usually acceptable, since less memory is used by the result than is needed during the fit.   But in cases where multiple models are fit in succession, one can quickly run out of memory unless the unused portions of the result are immediately nulled.  

The solution isn't too difficult[1], but the problem is that each model may require that slightly different pieces be kept for prediction to work, and each model may have different items that should be removed.   Standardizing each underlying package is at this point an impossible task.  But since Caret is already providing a unified interface on top of these disparate models, it is perfectly positions to fix this problem.  It would only require adding a 'trim' method to the interface that already exists for each wrapped model.   

@az0 brought this up in #76, but there didn't seem to be a clear resolution. @zachmayer and @jknowles discuss their intent to handle this in https://github.com/zachmayer/caretEnsemble/issues/69, but Caret seems like a much better place to put such functionality.  If it's not in Caret itself, every other package that deals with collections of Caret models would  have to add its own ersatz version for some subset of models.  

Would it be possible to add this functionality to Caret?  Ideally, this trimming would happen by default before a model is returned from 'fit', and an explicit 'trim=FALSE' type argument would be required prevent it from happening.   Or it could be specified as a generic postProcessing step that defaults to trim.model.  Either of these could be added immediately with default method does nothing, and per model trimming could be added as time goes on.

[1] http://www.win-vector.com/blog/2014/05/trimming-the-fat-from-glm-models-in-r/

**Comment by topepo** [comment] 2015-01-18 01:30
Thinking about this a little, I decided to remove the S3 method `trim` and put another element into the model code accessed by `getModelInfo`. The main reason for this is to keep all of the individual model's code is contained in these files (like all of the other components). 

Tests were added for `rpart`, `rpart2` and `treebag` as these are the only currently implemented. 

This might mess-up Zach's last  caretEnsemble commit (sorry) but we should be able to write an S3 method that accesses the trimming code. There are some difference in the method code and the class name (e.g. `method="rpart2"` produces class `rpart`) but some simple logic can resolve this.

**Comment by zachmayer** [comment] 2015-01-21 19:18
I think that makes sense. `getModelInfo` is the correct spot to keep all model-specific code.  
    
As far as an S3 method, maybe we only need `trim.train` for now? It would remove the pred object, resamples, and anything else not needed for prediction and then execute the correct trim function on the `finalModel`?
    
Then I can write a `trim.caretEnsemble` method that trims the caretEnsemble and then executes `trim.train`.

**Comment by jknowles** [comment] 2015-01-21 20:13
This makes a lot of sense to me. I don't think it would be hard to set out some goals for adding the trim methods to other models and asking the community to pitch in. I know I have a number of models that I use that I have pondered how to trim down in my work and would happily figure out how to do that in a way that fits within the caret package structure.

**Comment by zachmayer** [comment] 2015-01-21 20:55
I've already got dummy `trim` functions for `glm` and `bayesglm` in this PR:
https://github.com/topepo/caret/pull/106

I think the trim code for `lm` objects will be pretty similar to that for `glm`.

**Comment by topepo** [comment] 2015-01-28 16:16
I added trimming for C5 and glmnet models. 

I also looked at the set of objects from the last time that I ran the regression tests. The data used to get is not always the same but I thought that I could use the object sizes for these to look around (code at the very end).

The things that jumped out are that the model calls are, in some cases, the majority of the footprint. In most cases, this is because of `train`. Depending on how the tuning parameters are listed in the syntax, there are cases when the function is invoked via something like `do.call("function_name", list(x = x, y = y))`. This basically saves copies of the data in textual form. This isn't too much of a surprise. There are some old-school functions that use the information in the call (`earth` is one IIRC). 

Formula methods tend to have larger footprints compared to the alternative, most likely due to the inefficient `terms` object. There's nothing that I know to do about that. 

I think the next set of functions for me to focus on are those from `RWeka` since they use the `do.call` approach. I'm also going to get rid of the calls for any models defined in the package (e.g. `avNNet` etc). 

    setwd("~/tmp/2014_12_31_20__6.0-40")
    
    rd_files <- list.files(pattern = "RData$")
    rd_files <- rd_files[!grepl("(trim)|(rfe)|(sbf)", rd_files)]
    
    
    sizes <- data.frame(size = rep(NA, length(rd_files)),
                        form_size = rep(NA, length(rd_files)),
                        call_size = rep(NA, length(rd_files)),
                        model = gsub("\\.RData", "", rd_files))
    
    keepers <- c("i", "sizes", "rd_files", "keepers", "has.call")
    
    
    ## is.call not accurate for gam models
    has.call <- function(x) {
      call_name <- NULL
      if(!isS4(x)) {
        has_call <- unlist(lapply(x, function(x) any(class(x) == "call")))
        if(any(has_call)) call_name <- names(has_call)[has_call]
      } else {
        obj_names <- slotNames(x)
        for(j in obj_names) {
          if(any(class(getElement(x, j)) == "call")) call_name <- j
        }
      }
      call_name
    }
    
    
    for(i in 1:nrow(sizes)) {
      cat(rd_files[i], "\n")
      load(rd_files[i])
      test_obj <- ls(pattern = "test_")
      sum_noform <- sum_form <- sum_call <- 0
      num_noform <- num_form <- num_call <- 0
      
      if("test_class_cv_model" %in% test_obj) {
        if("terms" %in% tolower(names(test_class_cv_model$finalModel))) {
          sum_form <- sum_form <- object.size(test_class_cv_model$finalModel)  
          num_form <- num_form + 1
        } else {
          sum_noform <- sum_noform <- object.size(test_class_cv_model$finalModel)  
          num_noform <- num_noform + 1      
        }
        call_name <- has.call(test_class_cv_model$finalModel)
        if(!is.null(call_name)) {
          sum_call <- sum_call <- object.size(getElement(test_class_cv_model$finalModel, call_name))
          num_call <- num_call + 1        
        }
      } 
      
      if("test_reg_cv_model" %in% test_obj) {
        if("terms" %in% tolower(names(test_reg_cv_model$finalModel))) {
          sum_form <- sum_form <- object.size(test_reg_cv_model$finalModel)  
          num_form <- num_form + 1
        } else {
          sum_noform <- sum_noform <- object.size(test_reg_cv_model$finalModel)  
          num_noform <- num_noform + 1      
        }
        call_name <- has.call(test_reg_cv_model$finalModel)
        if(!is.null(call_name)) {
          sum_call <- sum_call <- object.size(getElement(test_reg_cv_model$finalModel, call_name))
          num_call <- num_call + 1        
        }   
      }  
      
      if(num_noform > 0) sizes$size[i] <- sum_noform/num_noform
      if(num_form > 0) sizes$form_size[i] <- sum_form/num_form  
      if(num_call > 0) sizes$call_size[i] <- sum_call/num_call  
      rm(list = ls()[!(ls() %in% keepers)])
    }
    
    sizes <- sizes[!apply(sizes[, 1:2], 1, function(x) all(is.na(x))), ]
    sizes$max_size <- apply(sizes[, 1:2], 1, max, na.rm = TRUE)
    sizes$pct_call <- sizes$call_size/sizes$max_size*100
    
    tail(sizes[order(sizes$max_size),])
    tail(sizes[order(sizes$pct_call, na.last = FALSE),])

**Comment by zachmayer** [comment] 2015-01-28 16:26
Hmmm, good point about `do.call`.  I use that to fit the models in `caretEnsemble`, and probably need to change that too.

**Comment by topepo** [comment] 2015-04-20 01:33
This has been implemented for models `bayesglm`, `C5.0`, `C5.0Cost`, `C5.0Rules`, `C5.0Tree`, `glm`, `glmnet`, `rpart`, `rpart2`, and `treebag`. The current regression tests are passing.

I'm going to close this and we can open new issues for specific models.

**Closed by topepo** 2015-04-20 01:33 UTC
Labels: enhancement
