### ISSUE TITLE
avMxnet is not a valid caret model

### ISSUE THREAD

**Issue by sparcycram** [topepo/caret#457] opened 2016-07-13 10:47 UTC
I am unable to make avMxnet run it gives the following error:-

Model avMxnet is not in caret's built-in library

I see that on the caret homepage mxnet exists?

The code that fails is posted below

library(MASS)
data("Aids2")
TRAIN <- as.data.frame(Aids2)
training_x <- subset(TRAIN, select = -c(status))

library("caret")
library("caretEnsemble")
library("glmnet")
library("mxnet")
library("drat")
library("arm")

my_control <- trainControl(
  method='cv',
  number=2,
  repeats =3,
  classProbs=TRUE,
  summaryFunction= twoClassSummary
)

set.seed(1234)
avMxnetFit1 <- train(
  training_x, TRAIN$status,
  trControl=my_control,
  metric= "ROC", 
  method = "avMxnet")
    

avMxnetFit1

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] arm_1.8-6           lme4_1.1-12         drat_0.1.0          mxnet_0.7          
 [5] glmnet_2.0-5        foreach_1.4.3       Matrix_1.2-6        caretEnsemble_2.0.0
 [9] caret_6.0-70        ggplot2_2.1.0       lattice_0.20-33     MASS_7.3-45        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5        nloptr_1.0.4       plyr_1.8.4         iterators_1.0.8    tools_3.3.1       
 [6] digest_0.6.9       jsonlite_1.0       nlme_3.1-128       gtable_0.2.0       mgcv_1.8-12       
[11] rstudioapi_0.6     parallel_3.3.1     SparseM_1.7        coda_0.18-1        gridExtra_2.2.1   
[16] DiagrammeR_0.8.2   stringr_1.0.0      htmlwidgets_0.6    MatrixModels_0.4-1 stats4_3.3.1      
[21] grid_3.3.1         nnet_7.3-12        data.table_1.9.6   pbapply_1.2-1      minqa_1.2.4       
[26] reshape2_1.4.1     car_2.1-2          magrittr_1.5       scales_0.4.0       codetools_0.2-14  
[31] htmltools_0.3.5    splines_3.3.1      abind_1.4-3        pbkrtest_0.4-6     colorspace_1.2-6  
[36] quantreg_5.26      stringi_1.1.1      visNetwork_1.0.1   munsell_0.4.3      chron_2.3-47

**Comment by zachmayer** [comment] 2016-07-13 12:32
Did you install caret from CRAN?  I don't think the mxnet models are in the CRAN version of caret yet.

**Comment by topepo** [comment] 2016-07-13 13:23
The code for the models are checked into github ([here](https://github.com/topepo/caret/blob/master/models/files/avMxnet.R) and [here](https://github.com/topepo/caret/blob/master/models/files/mxnet.R)) but are not in the CRAN version.

The current issue is that, last time I looked, there is no way to save the model object inside of a `train` object and be able to reload it later. It will run fine in the same session (since the model is still in memory) but I don't see any way to embed it inside another object.

**Comment by sparcycram** [comment] 2016-07-13 16:41
I installed caret from github directly. That also didn't work. If I am understanding this correctly I should load the code directly into a script and then run mxnet in caret?

Thanks

**Comment by topepo** [comment] 2016-07-13 18:02
For now, yes that is the best approach. I also need to update it to work
with regression models (right now, my code is classification only).

**Closed** 2016-07-18 12:24 UTC
