### ISSUE TITLE
scaling preds to original outcome distribution when down/upsampling

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#460] opened 2016-08-01 21:03 UTC
I used downsample and upsample on a classification problem today. I noticed that when the distribution is altered, such alteration is reflected on the predict function. I would suggest to make caret's predict to be scaled to original outcome variable distribution. I found the issue when upscaling, not sure for other modifications

**Comment by topepo** [comment] 2016-08-02 00:07
It is difficult to understand without a reproducible example. 

> I would suggest to make caret's predict to be scaled to original outcome variable distribution

Again, there is not enough specificity so some examples would help.

**Comment by spedygiorgio** [comment] 2016-08-05 21:05
[tocheck.zip](https://github.com/topepo/caret/files/404612/tocheck.zip)
I have attached a data file containing data and model

`library(data.table) #need to open data
library(caret)
library(C50)  

load(file="z:/tocheck.RData")

 predictors.categorical<-c("bonusMalus","policyLimit","vehicleFuelType",
                      "territoryBigCity","policyholderGender","policyholderOccupation","policyholderMaritalStatus",
                           "previousCompany","policyholderTerritory","vehicleKm","vehicleUsage",
                           "vehicleMakeAndModel"
 )
# 
# 
 predictors.continuous<-c("vehiclePower","vehicleAge","vehiclePurchaseAge","policyholderAge","quoteTimeToPolicy",
                          "ratioCompanyMkt","deltaCompanyMkt")



 c50Grid <- expand.grid(winnow = c(TRUE,FALSE), 
                        trials=c(1,5,10,20), 
                        model=c("tree","rules"))
 
 caretTrainCtrl2<-caretTrainCtrl
 caretTrainCtrl2$sampling="down" #need to downsample
cl<-makeCluster(cores)
 registerDoParallel(cl)
 C5.0.model<- train(x=dbtrain[,c(predictors.continuous,predictors.categorical),with=FALSE],
                    y=dbtrain$converted,
                    method = "C5.0",
                    tuneGrid = c50Grid,
                    trControl = caretTrainCtrl2,
                    metric = "Kappa",
                    importance=TRUE)  
 stopCluster(cl)



table(dbtest$converted)
dbtest$predC50<-predict(object = C5.0.model, newdata = dbtest, type="prob")[,"Y"]

mean(dbtest$predC50) #simulated distribution
prop.table(table(dbtest$converted)) #true distribution
`
simulated distribution too much different from actual, need scaling

**Comment by rwarnung** [comment] 2016-08-11 15:14
To a certain extent this seems to be connected to platt-scaling.
Recently there was code about this posted [here](https://www.analyticsvidhya.com/blog/2016/07/platt-scaling-isotonic-regression-minimize-logloss-error/).

In fact for platt scaling you put in a meta model where the task is to calibrate a logistic regression where the target is the original target and the data are the "probabilities" (often only scores) of you primary algorithm.

In the blog they write about isotonic regression too .. this should result in something similar - but I don't know enough to say.

I think this is quite standard in scikit-learn and also described [here](http://scikit-learn.org/stable/modules/calibration.html).

I wrote code for myself in caret to do this. It takes the train set, returns the platt-scaling (a glm) and returns the scaled probabilities for a new set of probabilies.

getPlattScaling<-function(probtrain,testingtarget,probnew){
meta.data = data.frame(prob=probtrain,target=testingtarget)
platt.model = train(target~prob,data = meta.data,
method="glm",family=binomial,
trControl = trainControl(method="none"), metric = "logLoss")
return(list(pred=predict(platt.model,newdata=data.frame(prob=probnew),type="prob"),platt.model=platt.model))
}

**Comment by spedygiorgio** [comment] 2016-09-09 09:33
A possible solution could be scaling the predicted probabilities for upsample/downsampled models to the average unscaled value.

**Comment by topepo** [comment] 2017-04-13 20:05
I'm going to close this but reopen if you feel the need to. A great solution would be to have some `caret` independent code that would do this in general (assuming that there isn't anything out there).

**Closed by topepo** 2017-04-13 20:05 UTC

**Comment by spedygiorgio** [comment] 2017-04-18 20:46
Hi Max,
my opinion is to reopen. A reasonable expectation is that  the predicted
probabilities to be unbiased regardless the sampling....

For example, to have unbiased estimated on a downsampled Naive Bayes I
computed a scaling factor

#computing biaseness correction, after train...
model.nb.correction<-(sum(dbtrain$converted=='Y'))/sum(predict(model.nb.down,newdata
= dbtrain[,nb.preds,with=FALSE],prob")["Y"][,1])
#predict
dbtest$probNb<-predict(model.nb.down,
newdata=dbtest,type="prob")["Y"][,1]*model.nb.correction





ᐧ

2017-04-13 22:05 GMT+02:00 Max Kuhn <notifications@github.com>:
