### ISSUE TITLE
caret::train requires excessive amounts of memory with the xgbTree method

### ISSUE THREAD

**Issue by ldesousa** [topepo/caret#880] opened 2018-05-09 06:36 UTC
This is a follow up to issue #870. `caret::train` is gobbling up memory to exhaustion with a 2 GB regression matrix, which I initially thought was cased by the number of sub-processes it triggers (taking up all of the available CPUs). After learning about the `nthread` argument I was able to control the number of CPUs used, however, the memory issues did not go away. Even with a single CPU `caret::train` exhausts the 26 GB of RAM in my workstation and is terminated by the OS.

I thus [sought help with the XGBoost community](https://groups.google.com/forum/#!topic/xgboost-user/FFw9VpsEch8). The full enquiry:

> I am presently working with an R script that trains a model using the *xgbTree* method through the `caret::train` function. Something like:
> 
> `mXGB <- caret::train(theFormula, data=dfs, method="xgbTree", trControl=ctrl, tuneGrid=gb.tuneGrid, nthread=2) `
> 
> The dfs dataset takes up about 2 GB of RAM. However, as the training starts, those two processes start consuming memory up to exhaustion. This is in a workstation with 26 GB of RAM.
> 
> Why is this method taking up so much memory? Is there any way to manage memory with this method? 
> 
> The software I am using:
> R 3.4.4
> caret 6.0.79
> xgboost 0.6.4.1

The reply sheds some light into it:

> Don't use caret::train's formula interface in this case. Its internal 
> processing does not take advantage of XGBoost's data structures, so it's 
> making a separate data frames for each CV fold, then another copy for 
> each fold to construct an xgb.DMatrix etc., so e.g. in a 10-fold CV it 
> may make at least 20 copies of your data. That was the state of caret's 
> code last time I tried doing what you do, and I suspect this didn't 
> change if you're reporting it. I remember inspecting caret::train's code 
> and noting that making it work well would be quite a lot of work too. 
> 
> I think if you convert your data into an xgb.DMatrix and then call 
> `caret::train` using its the matrix interface, it might be fine. But I 
> remember having problems even with this approach. 
> 
> The R package of XGBoost has `xgb.cv` for cross-validation. It's simpler 
> than `caret::train`: you'll probably need to explicitly convert your 
> data frame into an `xgb.DMatrix` and perform preprocessing, a loop over 
> your parameter grid, etc. But then memory usage will be under control. 
> 
> I usually end up writing the whole process from scratch anyway, using 
> bare `xgb.train` or even calling the predict/update functions 
> explicitly. Somehow almost every time I use XGBoost models, some custom 
> need shows up demanding a non-trivial change to training or validation 
> schemes… 

This explains why `caret::train` is exhausting memory regardless of the number of sub-processes spawned by the `xgboost` routines.

My next step is to try the `xgb.DMatrix` data structure, but it seems to me that there is something wrong in requiring 40 GB of RAM to process a 2 GB dataset. If in fact `caret::train` is being used correctly.

**Comment by topepo** [comment] 2018-05-09 19:49
A _small_, reproducible example and the results of `sessionInfo()` (per the issue template!) would help here. 

I don't necessarily agree with some of the comments above but, until there is something to look at, there's no way to tell. For example, I don't think that the comments about the number of data copies is accurate.

**Comment by ldesousa** [comment] 2018-05-10 08:40
@topepo I can not share the dataset, since it includes data unlicensed for publication. But I shall come up with a synthetic example.
I can guarantee from my experience that the memory required by this method is certainly more than 10 times that of the regression matrix. The comment in the XGBoost list looks entirely reasonable.

**Comment by Japrin** [comment] 2018-05-26 03:57
I also come across this issue.  Training data is a  xgb.DMatrix with dimention 500(samples) x 755 (variables), only 42888 bytes checked by object.size(). If I do repeated 10X cross-validation, it will take up all the memory and will be terminated by the system. I can share the sample data and code later for reproducing the result.

**Comment by topepo** [comment] 2018-05-26 04:35
Again, as the issue template says, a _small_, reproducible example and the results of `sessionInfo()` is how this will be solved. Dummy up a dataset that has the same issue.

**Comment by Japrin** [comment] 2018-05-26 11:18
@topepo 
Hi topepo, I make a small dataset, you can find here:[https://www.kaggle.com/japrin/example-code-to-reproduce/data]. 

I set the tree_method to "gpu_hist". I can run the dataset (even bigger) using the xgboost's xgb.cv() successfully. When the train() run to "Fold09.Rep04" (see below), the process was terminated by the system.

Hope this information can help you figure out what cause the problem.

Thanks in advance!

**The R code I usae:**
`library("data.table")
library("xgboost")
library("caret")

print(sessionInfo())

dat.train <- xgb.DMatrix("data.small.xgb.DMatrix.RData")
colnames(dat.train) <- sprintf("V%04d",seq_len(ncol(dat.train)))
dat.train.y <- sprintf("C%02d",getinfo(dat.train,"label"))
dat.train.y <- factor(dat.train.y,levels=sort(unique(dat.train.y)))

fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 10,
						   allowParallel=F,
						   verboseIter = T, classProbs = T,
						   savePredictions = "all",returnData=F)
xgboostGrid <-  expand.grid(max_depth=c(6),
							nrounds=c(100),
							eta=c(0.3),
							gamma = c(0),
							colsample_bytree=1,
							min_child_weight=1,
							subsample=1)
	
print(fitControl)
print(xgboostGrid)
model <- train(dat.train,dat.train.y, method = "xgbTree", 
			   trControl = fitControl,tuneGrid=xgboostGrid,verbose=T,
			   tree_method="gpu_hist",nthread=1)
print(model)
save(model,file = sprintf("reproduce.caret.RData"))`

**The session info:**
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

Matrix products: default
BLAS/LAPACK: /lustre1/japrin/01.bin/R/MKL/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

other attached packages:
[1] caret_6.0-79      ggplot2_2.2.1     lattice_0.20-35   xgboost_0.71.1   
[5] data.table_1.11.2 magrittr_1.5     

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4   purrr_0.2.4        reshape2_1.4.3     kernlab_0.9-26    
 [5] splines_3.4.3      colorspace_1.3-2   stats4_3.4.3       geometry_0.3-6    
 [9] prodlim_2018.04.18 survival_2.42-3    rlang_0.2.0        ModelMetrics_1.1.0
[13] pillar_1.2.2       withr_2.1.2        foreign_0.8-70     glue_1.2.0        
[17] bindrcpp_0.2.2     foreach_1.4.4      bindr_0.1.1        plyr_1.8.4        
[21] lava_1.6.1         dimRed_0.1.0       robustbase_0.93-0  stringr_1.3.0     
[25] timeDate_3043.102  munsell_0.4.3      gtable_0.2.0       recipes_0.1.2     
[29] codetools_0.2-15   psych_1.8.4        magic_1.5-8        parallel_3.4.3    
[33] class_7.3-14       DEoptimR_1.0-8     broom_0.4.4        methods_3.4.3     
[37] Rcpp_0.12.17       scales_0.5.0       ipred_0.9-6        CVST_0.2-1        
[41] abind_1.4-5        mnormt_1.5-5       stringi_1.2.2      dplyr_0.7.4       
[45] RcppRoll_0.2.2     ddalpha_1.3.3      grid_3.4.3         tools_3.4.3       
[49] lazyeval_0.2.1     tibble_1.4.2       tidyr_0.8.0        DRR_0.0.3         
[53] pkgconfig_2.0.1    MASS_7.3-50        Matrix_1.2-14      lubridate_1.7.4   
[57] gower_0.1.2        assertthat_0.2.0   iterators_1.0.9    R6_2.2.2          
[61] rpart_4.1-13       sfsmisc_1.1-2      nnet_7.3-12        nlme_3.1-137      
[65] compiler_3.4.3    

**output from stdout of train()**
  max_depth nrounds eta gamma colsample_bytree min_child_weight subsample
1         6     100 0.3     0                1                1         1
+ Fold01.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold01.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold02.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold02.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold03.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold03.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold04.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold04.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold05.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold05.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold06.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold06.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold07.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold07.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold08.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold08.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold09.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold09.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold10.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold10.Rep01: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold01.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold01.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold02.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold02.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold03.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold03.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold04.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold04.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold05.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold05.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold06.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold06.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold07.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold07.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold08.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold08.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold09.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold09.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold10.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold10.Rep02: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold01.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold01.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold02.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold02.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold03.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold03.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold04.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold04.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold05.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold05.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold06.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold06.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold07.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold07.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold08.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold08.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold09.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold09.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold10.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold10.Rep03: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold01.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold01.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold02.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold02.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold03.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold03.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold04.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold04.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold05.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold05.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold06.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold06.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold07.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold07.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold08.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
- Fold08.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 
+ Fold09.Rep04: max_depth=6, nrounds=100, eta=0.3, gamma=0, colsample_bytree=1, min_child_weight=1, subsample=1 

**output from stderr of train()**
terminate called without an active exception
/var/spool/rmd.spool/job9558389/slurm_script: line 22:  3458 Aborted                 (core dumped) ./reproduce.R

**Comment by Japrin** [comment] 2018-05-28 07:36
@topepo @ldesousa 
I think this problem is related with a issue of xgboost's issue [3045](https://github.com/dmlc/xgboost/issues/3045) . Maybe in the caret package,  in some place, the object returned by xgboost::xgb.train() should be deleted (by rm() or set it to NULL) than call gc().  If the object is needed, it can be saved to the disk by xgboost::xgb.save() before the deletion operation.
This works for me when I use my own code implementing repeated cross-validation.

**Comment by ldesousa** [comment] 2018-05-29 08:33
@topepo My apologies for the delay, it took me a while to figure out random number generation in R. The example below creates a `data.frame` object with 1.6 GB that is then passed to `caret::train`. It goes on to consume 20 GB of RAM, at which point this particular system became unresponsive and the job had to be terminated.

```
library(caret) # 6.0.79
library(xgboost) # 0.6.4.1

# Column names
cols <- sprintf("VAR%s",seq(1:200))

# Create data.frame with random values
dfs <- data.frame(matrix(rnorm(201 * 1e6), ncol=201))

# Add column names
colnames(dfs) <- union("TARGET", cols)

formulaString <- as.formula(paste('TARGET ~ ', paste(cols, collapse="+")))

ctrl <- trainControl(method="repeatedcv", number=3, repeats=1)

gb.tuneGrid <- expand.grid(
		eta = c(0.3,0.4,0.5), 
		nrounds = c(50,100,150), 
		max_depth = 2:4, gamma = 0, 
		colsample_bytree = 0.8, 
		min_child_weight = 1, 
		subsample=1)

mgbX <- caret::train(
		formulaString, 
		data=dfs, 
		method="xgbTree", 
		trControl=ctrl, 
		tuneGrid=gb.tuneGrid, 
		nthread=4)
```

@Japrin Thank you for example too.

**Comment by hadjipantelis** [comment] 2018-05-30 11:59
@ldesousa Can you please update your XGBoost in the latest CRAN stable 0.71.1? I just rerun your example on my systems, R stabilised at ~8.85GB. (8.8GB on R 3.4.0 on RHEL and 8.9GB on R 3.4.1 on Windows 7).

**Comment by ldesousa** [comment] 2018-05-31 11:21
@hadjipantelis Thank you for chiming in. I upgraded `xgboost` to 0.71.1 and indeed memory consumption is different. It now peaks at 18 GB and it takes considerably longer to get to that figure (this means `caret::train` not finishes successfully in this workstation). Still, that is well over 10 times the size of the regression matrix, therefore I will leave this issue open.

**Comment by crj32** [comment] 2018-06-19 16:10
I had a similar problem this afternoon, essentially, high p low N, and svm radial, random forest, and glmnet worked fine. Then most algorithms involving boosting I tried like gbm or xgboost just hang the computer and I have 32GB of RAM. Anything involving boosting seemed to screw the system up and naive bayes. Maybe this is too big a problem to fix sorry Max.

**Comment by ldesousa** [comment] 2018-06-20 12:05
@topepo I see this is still marked as `cannot reproduce`, could you please detail how is the example running on your side? Or with which packages versions you are working? Thank you.

**Comment by topepo** [comment] 2018-06-20 17:19
I haven't had the time to look at this in detail yet. I'll get through some deadlines in the next few days then get on it.

**Comment by hadjipantelis** [comment] 2018-06-22 14:14
@crj32 : Can you please provide an example with `gbm`? `gbm` and `xgboost` are different implementations so it is unlikely they have the same root cause.

For the XGBoost part: Maybe https://github.com/dmlc/xgboost/issues/3045 and the associated PR by @Japrin https://github.com/topepo/caret/pull/893 fix this...

**Comment by topepo** [comment] 2018-08-17 14:47
I'm going to close this and #893 TBH I don't like the implementation and it appears to be an `xgboost` issue.

**Closed by topepo** 2018-08-17 14:47 UTC
Labels: reproducible
