### ISSUE TITLE
varImp for randomForest

### ISSUE THREAD

**Issue by blueskypie** [topepo/caret#333] opened 2015-11-27 23:49 UTC
why is the output for varImp(train) different from randomForest:::importance(train$finalModel)?

Thanks!

**Comment by topepo** [comment] 2015-11-29 23:10
Providing a reproducible example and the results of `sessionInfo` will help get your question answered.

**Comment by blueskypie** [comment] 2015-11-30 15:04
Thanks for the quick response! My data are too big but I'll try to make a small example. Meanwhile, if I'm using the "rf" method, does it work with the "cforest" below? If not, is there a way to change cforest to rf?

#> getAnywhere(varImp.RandomForest)
	#A single object matching 'varImp.RandomForest' was found
	#It was found in the following places
	#registered S3 method for varImp from namespace caret
	#namespace:caret
	#with value
	#
	#function(object, ...){
	#	code <- varImpDependencies("cforest")
	#	code$varImp(object, ...)
	#}
	#<environment: namespace:caret>

**Comment by topepo** [comment] 2016-04-19 15:13
I'm going to close this due to no data for reproducing the issue.

**Closed by topepo** 2016-04-19 15:13 UTC
