### ISSUE TITLE
sample() gotcha with 1-observation class

### ISSUE THREAD

**Issue by HarlanH** [topepo/caret#115] opened 2015-02-04 22:49 UTC
When training on categorical data where the outcome vector is almost-degenerate, with 1 "Yes" and lots of "No"s, I'm getting the following error.

```{R}
 In foldVector[which(y == dimnames(numInClass)$y[i])] <- sample(seqVector) :
  number of items to replace is not a multiple of replacement length
```

Line 50 of createFolds.R.

I'm pretty sure that this is the infamous design error with `sample`, and that seqVector must unexpectedly be a single number here.

**Comment by zachmayer** [comment] 2015-02-04 22:57
Could you post an example that produces this problem?

**Comment by HarlanH** [comment] 2015-02-04 23:17
This does it for me (using the trainControl I'm actually using -- not sure which of those are required):

```r
library(caret)

dd <- data.frame(y=c(rep("No", 100), "Yes"),
                 x=rnorm(101))

train(y ~ x, dd, trControl= trainControl(method = "cv", number = 5, classProbs = TRUE, 
                                         summaryFunction = twoClassSummary, 
                                         returnResamp = "final", allowParallel=FALSE,
                                         verboseIter=TRUE))
```

```
Loading required package: randomForest
randomForest 4.6-10
Type rfNews() to see new features/changes/bug fixes.
+ Fold1: mtry=2 
- Fold1: mtry=2 
+ Fold2: mtry=2 
model fit failed for Fold2: mtry=2 Error in randomForest.default(x, y, mtry = param$mtry, ...) : 
  Need at least two classes to do classification.
 
- Fold2: mtry=2 
+ Fold3: mtry=2 
- Fold3: mtry=2 
+ Fold4: mtry=2 
- Fold4: mtry=2 
+ Fold5: mtry=2 
- Fold5: mtry=2 
Aggregating results
Error in train.default(x, y, weights = w, ...) : 
  final tuning parameters could not be determined
In addition: Warning messages:
1: In foldVector[which(y == dimnames(numInClass)$y[i])] <- sample(seqVector) :
  number of items to replace is not a multiple of replacement length
2: In train.default(x, y, weights = w, ...) :
  The metric "Accuracy" was not in the result set. ROC will be used instead.
3: In randomForest.default(x, y, mtry = param$mtry, ...) :
  invalid mtry: reset to within valid range
4: In eval(expr, envir, enclos) :
  model fit failed for Fold2: mtry=2 Error in randomForest.default(x, y, mtry = param$mtry, ...) : 
  Need at least two classes to do classification.

5: In randomForest.default(x, y, mtry = param$mtry, ...) :
  invalid mtry: reset to within valid range
6: In randomForest.default(x, y, mtry = param$mtry, ...) :
  invalid mtry: reset to within valid range
7: In randomForest.default(x, y, mtry = param$mtry, ...) :
  invalid mtry: reset to within valid range
8: In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.
9: In train.default(x, y, weights = w, ...) :
  missing values found in aggregated results
```

**Comment by zachmayer** [comment] 2015-02-05 14:08
This seems to be the minimum needed to replicate the problem:
```{R}
library(caret)
dd <- data.frame(y=c(rep("No", 100), "Yes"),x=rnorm(101))
train(y ~ x, dd, trControl= trainControl(method = "cv", number = 5, verboseIter=TRUE))
```

The relevant warning seems to be:
```{R}
Warning messages:
1: In foldVector[which(y == dimnames(numInClass)$y[i])] <- sample(seqVector) :
  number of items to replace is not a multiple of replacement length
```

You get the same result using the non-formula interface.
```{R}
library(caret)
dd <- data.frame(y=c(rep("No", 100), "Yes"),x=rnorm(101))
train(data.frame(x=dd$x), dd$y, trControl= trainControl(method = "cv", number = 5, verboseIter=TRUE))
```

**Comment by topepo** [comment] 2015-02-11 03:57
Throwing an error is bad but what do you expect the result to be? If there are not enough instances within a class, I would propose that an overall un-stratified random sample be used.

**Comment by HarlanH** [comment] 2015-02-11 12:16
Yes, I think that'd make sense. This is clearly a degenerate case -- I'm
not worried about getting predictive accuracy when there are 0 or 1
instances of one class, just that I get back a caret object with a predict
method in all cases, for programmatically-generated models. (I have a
workaround for the 0-instance case, but didn't expect a problem with the
1-instance case!) Thanks!

**Comment by drj571** [comment] 2015-04-14 17:22
I am having a similar problem with the following warning:
```{r}
Warning message:
In foldVector[which(y == dimnames(numInClass)$y[i])] <- sample(seqVector) :
  number of items to replace is not a multiple of replacement length
```
But when I run this in Weka with the same features and 10-fold CV I don't get a warning.

Here is a reproducible example:
```{r}
library(bnlearn)
library(caret)
library(klaR)
library(MASS)
train <- read.table("http://pshenoy.faculty.ku.edu/Datasets/Audiology-Train106.csv", sep = ",", 
                   header = TRUE)
train <- train[, -1]

## Run bnlearn to get Markov Blanket
q2AOut <- iamb(train)
## Get the values from the Markov Blanket
useTheseA <- mb(q2AOut, "class")

## Run Naive Bayes
x <- train[, useTheseA]
y <- train[, "class"]

model <- train(x, y, "nb", trControl = trainControl(method = "cv", number = 10))


```

In my case do I need to worry about this warning? If I run the same model in Weka with 10 fold CV (sorry for lack of an example) I don't get a warning. I am just wondering if this is something to be concerned about.

**Comment by topepo** [comment] 2015-04-20 21:48
Here is my proposal: any sample that is the single member of the class goes into the sample. This means that during CV, this sample will be in the modeling set (but that class is never held out). 

It issues a warning when classes have no members or only a single data point. 

Here is some code to test with:

```r
foo <- function (y, times = 1, p = 0.5, list = TRUE, groups = min(5, length(y))){
  out <- vector(mode = "list", times)
  
  if(length(y) < 2) stop("y must have at least 2 data points")
  
  if(groups < 2) groups <- 2
  
  if(is.numeric(y)) {
    y <- cut(y, 
             unique(quantile(y, probs = seq(0, 1, length = groups))), 
             include.lowest = TRUE)
  } else {
    xtab <- table(y)
    if(any(xtab == 0)) {
      warning(paste("Some classes have no records (", 
                    paste(names(xtab)[xtab  == 0], sep = "", collapse = ", "),
                    ") and these will be ignored"))
      y <- factor(as.character(y))
    } 
    if(any(xtab == 1)) {
      warning(paste("Some classes have a single record (", 
                    paste(names(xtab)[xtab  == 1], sep = "", collapse = ", "),
                    ") and these will be selected for the sample"))
    }    
  }
  
  subsample <- function(dat, p) {
    if(nrow(dat) == 1) {
      out <- dat$index
    } else {
      num <- ceiling(nrow(dat) * p)
      out <- sample(dat$index, size = num)
    }
    out  
  }
  
  for (j in 1:times) {
    tmp <- dlply(data.frame(y = y, index = seq(along = y)),
                 .(y), subsample, p = p)
    tmp <- sort(as.vector(unlist(tmp)))
    out[[j]] <- tmp
  }
  
  if (!list) {
    out <- matrix(unlist(out), ncol = times)
    colnames(out) <- caret:::prettySeq(1:ncol(out))
  } else {
    names(out) <- caret:::prettySeq(out)
  }
  out
}

library(plyr)
library(caret)
data(oil)

## make one sample class
test_dat <- oilType[-27]

pct <- .9
in_train <- foo(test_dat, list = FALSE, p = pct, times = 1)

cbind(all_data = table(test_dat), 
      expected_num = ceiling(table(test_dat)*pct), 
      in_subset = table(test_dat[in_train]), 
      out_of_subset = table(test_dat[-in_train]))
```

I'd like to release a new version within a week so please test this as much as you can. 

Thanks,

Max

**Comment by topepo** [comment] 2015-04-20 22:47
For K-fold CV, here is some updated code:

```r
"foo2" <- 
  function(y, k = 10, list = TRUE, returnTrain = FALSE) {
    
    if(is.numeric(y)) {
      ## Group the numeric data based on their magnitudes
      ## and sample within those groups.
      
      ## When the number of samples is low, we may have
      ## issues further slicing the numeric data into
      ## groups. The number of groups will depend on the
      ## ratio of the number of folds to the sample size.
      ## At most, we will use quantiles. If the sample
      ## is too small, we just do regular unstratified
      ## CV
      cuts <- floor(length(y)/k)
      if(cuts < 2) cuts <- 2
      if(cuts > 5) cuts <- 5
      breaks <- unique(quantile(y, probs = seq(0, 1, length = cuts)))
      y <- cut(y, breaks, include.lowest = TRUE)
    }
    
    if(k < length(y)) {
      ## reset levels so that the possible levels and 
      ## the levels in the vector are the same
      y <- factor(as.character(y))
      numInClass <- table(y)
      foldVector <- vector(mode = "integer", length(y))
      
      ## For each class, balance the fold allocation as far 
      ## as possible, then resample the remainder.
      ## The final assignment of folds is also randomized. 
      for(i in 1:length(numInClass)) {
        ## create a vector of integers from 1:k as many times as possible without 
        ## going over the number of samples in the class. Note that if the number 
        ## of samples in a class is less than k, nothing is producd here.
        min_reps <- numInClass[i] %/% k
        if(min_reps > 0) {
          spares <- numInClass[i] %% k
          seqVector <- rep(1:k, min_reps)
          ## add enough random integers to get  length(seqVector) == numInClass[i]
          if(spares > 0) seqVector <- c(seqVector, sample(1:k, spares))
          ## shuffle the integers for fold assignment and assign to this classes's data
          foldVector[which(y == names(numInClass)[i])] <- sample(seqVector)
        } else {
          ## Here there are less records in the class than unique folds so
          ## randomly sprinkle them into folds. 
          foldVector[which(y == names(numInClass)[i])] <- sample(1:k, size = numInClass[i])
        }  
      }
    } else foldVector <- seq(along = y)
    
    if(list) {
      out <- split(seq(along = y), foldVector)
      names(out) <- paste("Fold", gsub(" ", "0", format(seq(along = out))), sep = "")
      if(returnTrain) out <- lapply(out, function(data, y) y[-data], y = seq(along = y))
    } else out <- foldVector
    out
  }
```
examples

```r
library(caret)
data(oil)
fold_vals1 <- foo2(oilType, list = TRUE)
tabs1 <- lapply(fold_vals1, function(x, y) table(y[x])/table(y), y = oilType)
tabs1 <- do.call("rbind", tabs1)
```
and
```r
### Jared's example
library(bnlearn)
library(caret)
library(klaR)
library(MASS)
train <- read.table("http://pshenoy.faculty.ku.edu/Datasets/Audiology-Train106.csv", sep = ",", 
                   header = TRUE)
train <- train[, -1]

## Run bnlearn to get Markov Blanket
q2AOut <- iamb(train)
## Get the values from the Markov Blanket
useTheseA <- mb(q2AOut, "class")

## Run Naive Bayes
x <- train[, useTheseA]
y <- train[, "class"]
fold_vals2 <- foo2(y, list = TRUE)
tabs2 <- lapply(fold_vals1, function(x, y) table(y[x])/table(y), y = y)
tabs2 <- do.call("rbind", tabs2)
```

**Comment by topepo** [comment] 2015-05-08 18:11
fixed in current cran version

**Closed by topepo** 2015-05-08 18:11 UTC
Labels: next release
