### ISSUE TITLE
R caret: gafs nnet “undefined columns selected”

### ISSUE THREAD

**Issue by GYang14** [topepo/caret#1065] opened 2019-08-15 00:10 UTC
Hi Max,

I have enjoyed your great package caret through last couple years and finally got a small opportunity to make my own contribution through opening an issue, LoL. 

I am running into problems when applying feature selection using Genetic Algorithms to nnet models with gafs. I get the following error message:
```
Error in { : 
  task 1 failed - "task 1 failed - "undefined columns selected""
```

Could you please help?

Thank you very much.

**Here is a reproducible example;**

```r

library(caret)
data(cars)
set.seed(123)
seeds <- vector(mode = "list", length = 100)
for (i in 1:100)
  seeds[[i]] <- sample.int(8000, 8000)
trCtrl <- trainControl(
  method = "repeatedcv",
  number = 5,
  repeats = 1,
  seeds = seeds
)
ann_grid <- expand.grid(size = 10,
                        decay = 0.1)
set.seed(1056)
ga_seeds <- sample.int(1500, 51)
ga_ctrl <- gafsControl(
  functions = caretGA,
  method = "repeatedcv",
  repeats = 1,
  metric = c(internal = 'Rsquared', external = 'Rsquared'),
  maximize = c(internal = TRUE, external = TRUE),
  seeds = ga_seeds
)
ga_ann <-
  gafs(
    x = cars[, -which(names(cars) %in% c("Price"))],
    y = cars$Price,
    iters = 1,
    gafsControl = ga_ctrl,
    method = 'nnet',
    trControl = trCtrl,
    tuneGrid = ann_grid,
    preProcess = c("nzv", "range")
  )

**Below is the session information:**

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] recipes_0.1.6   dplyr_0.8.3     caret_6.0-84    ggplot2_3.2.0   lattice_0.20-38

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         pillar_1.4.2       compiler_3.6.1     gower_0.2.1        plyr_1.8.4        
 [6] iterators_1.0.12   class_7.3-15       tools_3.6.1        rpart_4.1-15       ipred_0.9-9       
[11] lubridate_1.7.4    tibble_2.1.3       nlme_3.1-140       gtable_0.3.0       pkgconfig_2.0.2   
[16] rlang_0.4.0        Matrix_1.2-17      foreach_1.4.7      prodlim_2018.04.18 stringr_1.4.0     
[21] withr_2.1.2        generics_0.0.2     stats4_3.6.1       grid_3.6.1         nnet_7.3-12       
[26] tidyselect_0.2.5   data.table_1.12.2  glue_1.3.1         R6_2.4.0           survival_2.44-1.1 
[31] lava_1.6.6         reshape2_1.4.3     purrr_0.3.2        magrittr_1.5       ModelMetrics_1.2.2
[36] scales_1.0.0       codetools_0.2-16   MASS_7.3-51.4      splines_3.6.1      assertthat_0.2.1  
[41] timeDate_3043.102  colorspace_1.4-1   stringi_1.4.3      lazyeval_0.2.2     munsell_0.5.0     
[46] crayon_1.3.4      
```

**Thank you very much!**

**Comment by topepo** [comment] 2019-09-20 14:03
Note to self; the issue is that the `nnet` predictions are a matrix and need to be converted to a vector

**Comment by topepo** [comment] 2020-01-03 00:58
It is fixed now (see below) but note that you should add `linout = TRUE` so that the network does not use a final softmax layer (which causes the predictions to be between `[0, 1]`). 

``` r
library(caret)
#> Loading required package: lattice
#> Loading required package: ggplot2
data(cars)
set.seed(123)
seeds <- vector(mode = "list", length = 100)
for (i in 1:100)
  seeds[[i]] <- sample.int(8000, 8000)
trCtrl <- trainControl(
  method = "repeatedcv",
  number = 5,
  repeats = 1,
  seeds = seeds
)
ann_grid <- expand.grid(size = 10,
                        decay = 0.1)
set.seed(1056)
ga_seeds <- sample.int(1500, 51)
ga_ctrl <- gafsControl(
  functions = caretGA,
  method = "repeatedcv",
  repeats = 1,
  metric = c(internal = 'Rsquared', external = 'Rsquared'),
  maximize = c(internal = TRUE, external = TRUE),
  seeds = ga_seeds
)
ga_ann <-
  gafs(
    x = cars[, -which(names(cars) %in% c("Price"))],
    y = cars$Price,
    iters = 1,
    gafsControl = ga_ctrl,
    method = 'nnet',
    trControl = trCtrl,
    tuneGrid = ann_grid,
    preProcess = c("nzv", "range"),
    trace = FALSE,
    # Add this some that the predictions are not constrained to 
    # be within [0, 1]
    linout = TRUE
  )
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
#> Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
#> There were missing values in resampled performance measures.

#> Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
#> There were missing values in resampled performance measures.

#> Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
#> There were missing values in resampled performance measures.

#> Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
#> There were missing values in resampled performance measures.

#> Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
#> There were missing values in resampled performance measures.

#> Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
#> There were missing values in resampled performance measures.
ga_ann
#> 
#> Genetic Algorithm Feature Selection
#> 
#> 804 samples
#> 17 predictors
#> 
#> Maximum generations: 1 
#> Population per generation: 50 
#> Crossover probability: 0.8 
#> Mutation probability: 0.1 
#> Elitism: 0 
#> 
#> Internal performance values: RMSE, Rsquared, MAE
#> Subset selection driven to maximize internal Rsquared 
#> 
#> External performance values: RMSE, Rsquared, MAE
#> Best iteration chose by maximizing external Rsquared 
#> External resampling method: Cross-Validated (10 fold, repeated 1 times) 
#> 
#> During resampling:
#>   * the top 5 selected variables (out of a possible 17):
#>     Cylinder (100%), Saab (100%), Cadillac (80%), convertible (80%), coupe (70%)
#>   * on average, 9.3 variables were selected (min = 5, max = 14)
#> 
#> In the final search using the entire training set:
#>    * 15 features selected at iteration 1 including:
#>      Mileage, Cylinder, Doors, Cruise, Sound ... 
#>    * external performance at this iteration is
#> 
#>           RMSE       Rsquared            MAE 
#>      5057.4771         0.7503      3375.0513
```

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed** 2020-01-03 01:35 UTC
Labels: bug, next release, reproducible
