### ISSUE TITLE
Change default arguments of ROC computation (pROC) in the RFE process (caret)

### ISSUE THREAD

**Issue by RafaOR** [topepo/caret#431] opened 2016-05-25 08:52 UTC
I am computing a SVM-RFE model using "ROC" as the metric with the `rfe` function of the `caret` package and I have noticed that there is no way to change the default arguments of the `roc` function (`pROC` package). In my case, for example, I would like to set the direction argument to `"<"` instead of `"auto"` because in some cases the resulting AUC is computed in reverse. Would it be possible to consider this enhancement?

**Comment by xrobin** [comment] 2016-05-25 12:46
This is actually an issue with worse classifiers with an AUC is close to 0.5. The AUC is systematically over-estimated with the default direction (auto) that will attempt to keep the AUC above 0.5 at all times. In general one should never use the default direction in a resampling operation.

The way I handle this in pROC with the bootstrapping operations is to compute the direction on the whole ROC curve, and keep that direction fixed during the resampling.
An alternative would be to simply fix the direction to "<". It is reasonable most of the time actually, as positive classifications are typically assigned to higher values. I am not very familiar with caret, so I am somewhat unsure if we can assume it will always be the case, but even if it is not it is probably better than the current state.

The ROC function from pROC seem to be called in 3 different places, in aaa.R and filterVarImp.R. I will try to submit a pull request with the latter approach.

**Comment by topepo** [comment] 2016-05-25 16:56
We need to be careful here. Right now, we assume that the first factor is the event of interest. That has been consistent in the documentation and teaching materials for some time. The changes should ensure that this design choice is not negated.

**Comment by xrobin** [comment] 2016-05-25 17:39
And pROC assumes that the level of interest is the second level of the factor, so we already have an inconsistency indeed, and relied on the direction="auto" argument. This is probably the biggest design mistake I did with pROC.

Ideally it would be best to have calls like this:

    levelOfInterest <- lev[1]
    levelOfNegatives <- lev[2]
    pROC::roc(obs, data[,class], direction = "<", levels = c(levelOfNegatives, levelOfInterest))

So two things are left:

* The levels are not available in rocPerCol. Can I assume that I will get them correctly if I do

    lev <- levels(cls) or could they end up being reversed?

* Do you always assume that the observations of interest will get higher predicted values, or could this be false in some cases?

**Comment by topepo** [comment] 2016-05-25 18:09
Here is how `rocPerCol` is used in `filterVarImp` (where the original outcome factor may have many levels):

```r
for (i in 1:k) {
  for (j in i:k) {
    if (i != j) {
      classIndex[[i]] <- c(classIndex[[i]], counter)
      classIndex[[j]] <- c(classIndex[[j]], counter)
      index <- which(y %in% c(classLevels[i], classLevels[j]))
      tmpX <- x[index, , drop = FALSE]
      tmpY <- factor(as.character(y[index]), levels = c(classLevels[i], classLevels[j]))
      tmpStat[, counter] <- apply(tmpX, 2, rocPerCol, cls = tmpY)
      counter <- counter + 1
    }
  }
}
```

In this case, we might want to reorder the classes based on their average value since there is no guarantee on the direction (and it is just being used to screen variables)

**Comment by xrobin** [comment] 2016-05-27 07:53
If it's used only for screening variables of unknown direction, then I guess it is safe to keep it on "auto" in `rocPerCol`.

**Comment by RafaOR** [comment] 2016-05-27 08:12
I think that I am not understanding everything you say (I have only been using R for a few months...)

What I am doing now is to recalculate the average AUC values with the `$pred` data of the RFE model for all the possible number of predictors, setting the `direction` argument to `"<"`, and then update the RFE model (with the function `update`) to the set of predictors with the best average AUC value.

Is this a good simple solution to the problem?

**Comment by topepo** [comment] 2016-05-27 12:44
The simplest short-term solution is to modify the `summary` components of the functions (as described [here](http://topepo.github.io/caret/rfe.html#rfe)) and change how `roc` is called.

**Comment by RafaOR** [comment] 2016-05-30 14:35
To this end, I have followed the instructions in your book Applied Predictive Modeling (very helpful by the way!). The code I use is:

```
fiveStats <- function(...) c(twoClassSummary(...), defaultSummary(...))
svmFuncs <- caretFuncs
svmFuncs$summary <- fiveStats
```

but I do not know how to change how `roc` is called. What should I do to change it?

**Comment by topepo** [comment] 2016-05-31 02:39
You are using `rfe`? If that's the case then pass it to the control function. [This page](http://topepo.github.io/caret/rfe.html#rfe) has details under "helper functions". If you are passing the `method` to `train`, then use something like 

```r
ctrl$functions <- caretFuncs
ctrl$functions$summary <- fiveStats
```

**Comment by topepo** [comment] 2016-06-11 22:38
Now that I've gotten around to running the regressions tests, I think that `twoClassSummary` should use ">" as the direction. 

It chooses the class probability associated with the first level of the factor to use to compute the ROC curve and that _should_ have the higher value (unless the model is degenerate somehow). 

 > `rocObject <- try(pROC::roc(data$obs, data[, lev[1]]), silent = TRUE)`

For example:

```r
> library(caret)
> library(pROC)
> 
> set.seed(346)
> dat <- twoClassSim(200)
> 
> set.seed(35)
> mod <- train(Class ~ ., data = dat,
+              method = "lda",
+              metric = "ROC",
+              trControl = trainControl(method = "cv",
+                                       savePredictions = TRUE,
+                                       summaryFunction = twoClassSummary, 
+                                       classProbs = TRUE))
> 
> 
> mod$finalModel$obsLevels[1]
[1] "Class1"
> 
> ggplot(mod$pred, aes_string(x = "obs", y = mod$finalModel$obsLevels[1])) +
+   geom_boxplot()
> 
> pROC::roc(mod$pred$obs, mod$pred$Class1, direction = "<")

Call:
roc.default(response = mod$pred$obs, predictor = mod$pred$Class1,     direction = "<")

Data: mod$pred$Class1 in 110 controls (mod$pred$obs Class1) < 90 cases (mod$pred$obs Class2).
Area under the curve: 0.09222
> pROC::roc(mod$pred$obs, mod$pred$Class1, direction = ">")

Call:
roc.default(response = mod$pred$obs, predictor = mod$pred$Class1,     direction = ">")

Data: mod$pred$Class1 in 110 controls (mod$pred$obs Class1) > 90 cases (mod$pred$obs Class2).
Area under the curve: 0.9078
```

**Comment by zijianding** [comment] 2016-06-16 01:22
I've come into this problem when using random forest as well. Here are the concerns:

1. Optimizing AUC values through actually the negative class (un-target class)
When training the best random forest model,  I use the AUC of ROC curve to find the best `mtry` parameter of rf. This will request the `trainControl` function to call `roc` function in pROC, which we can not modify the parameter of `roc`, including `levels` and `direction`

2. pROC package gives opposite AUC values when switching the positive and negative class
I am not quite sure why this happens, but we can prove that if the predictive scores are set, the AUC value keeps the same whether we switch the positive and negative class.

I can not fully understand the solutions mentioned above, so 
1) If I want to change the `direction` parameter of `roc` when calling `trainControl`, how can we achieve this?
2) Or is it possible to change to other package which takes the first level as target class, such as ROCR?

**Comment by topepo** [comment] 2016-06-16 13:27
@zijianding :

> This will request the trainControl function to call roc function in pROC, which we can not modify the parameter of roc, including levels and direction

You can change those parameters. [You can modify](http://topepo.github.io/caret/training.html#metrics) the `twoClalssSummary` function and pass it to `summaryFunction`. 

Probably the better bet would be to change the ordering of your factor outcome. `train` assumes that the first level is the event of interest. 

For #2, we would need a reproducible example to understand and comment.

**Comment by zijianding** [comment] 2016-06-17 02:36
@topepo :
Thank you!
I've followed your advice and here is the new code:
`twoClassSummary <- function(data, lev=NULL, model=NULL)
{
  if (length(levels(data$obs)) > 2) 
    stop(paste("Your outcome has", length(levels(data$obs)), 
               "levels. The twoClassSummary() function isn't appropriate."))
  #requireNamespace("pROC")
  library(pROC)
  if (!all(levels(data[, "pred"]) == levels(data[, "obs"]))) 
    stop("levels of observed and predicted data do not match")
  #rocObject <- try(pROC::roc(data$obs, data[, lev[1]]), silent = TRUE)
  rocObject <- try(pROC::roc(response=data$obs,predictor=data[, lev[1]],
                             levels=c(lev[2],lev[1]), direct="<"), silent=T )
  rocAUC <- if (class(rocObject)[1] == "try-error") 
    NA
  else rocObject$auc
  out <- c(rocAUC, sensitivity(data[, "pred"], data[, "obs"], 
                               lev[1]), specificity(data[, "pred"], data[, "obs"], lev[2]))
  names(out) <- c("ROC", "Sens", "Spec")
  out
}`

The major modification is that I pass the the target class `lev[1]` to the `roc` function as the second level.Also during the modification, a weird error happened that R cannot find the function `requireNamespace`,so I directly call the pROC package.

Anyhow I guess the codes run properly, thank you so much for your help!

**Comment by xrobin** [comment] 2016-07-03 13:13
Sorry for the late answer.

I agree with this fix. Setting direction = ">" is exactly equivalent to switching positive and negative observations and will make no difference to the AUC. Unless the ROC curve is exposed to the user at some point, it is perfectly fine.

One additional note, it looks like my previous pull request was merged so `rocPerCol` now uses the (wrong) direction. I can make a new pull request to revert this.

**Closed** 2020-08-19 17:05 UTC
